# Generated by Django 2.2.4 on 2019-08-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('glist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerysheetapp.GroceryList')),
            ],
        ),
    ]
