# Generated by Django 2.2.4 on 2019-08-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('glist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerysheetapp.GroceryList')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='people',
            field=models.ManyToManyField(blank=True, to='grocerysheetapp.Person'),
        ),
    ]
