# Generated by Django 2.2.4 on 2019-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0003_auto_20190817_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='buyer',
            field=models.CharField(default='Lee', max_length=255),
            preserve_default=False,
        ),
    ]
