# Generated by Django 2.2.4 on 2019-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0004_grocerylist_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
