# Generated by Django 2.2.4 on 2019-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0005_person_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
