# Generated by Django 2.2.4 on 2019-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerysheetapp', '0006_auto_20190818_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
